### ISSUE TITLE
Add warning that requires SBT 0.13.13+

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-project.g8#6]

**Comment by chuwy** [comment]
0.13.13 actually.

**Comment by alexanderdean** [comment]
Hmm, still not working:

```
vagrant@cranberry:/vagrant/foo$ sbt --version
sbt launcher version 0.13.8
vagrant@cranberry:/vagrant/foo$ sbt new snowplow/snowplow-scala-app.g8
[info] Set current project to foo (in build file:/vagrant/foo/)
[error] Not a valid command: new (similar: set)
[error] Not a valid project ID: new
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: new (similar: name, run, runner)
[error] new
[error]    ^
```

**Comment by chuwy** [comment]
`sbt launcher version 0.13.8` should be `0.13.13`.

**Comment by chuwy** [comment]
I'd recommend this launched https://github.com/paulp/sbt-extras

**Comment by alexanderdean** [comment]
So it doesn't work with 0.13.4+? We only have 0.13.2 and 0.13.8 in ansible-playbooks, so I don't really understand how I'm meant to use this.

**Comment by chuwy** [comment]
No, it works only with 0.13.13+. I didn't consider to use it in conjunction with ansible-playbooks as this is something bootstrapped from host, not from Vagrant box.
